// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  $('document').ready((function() {
    var session, stateLoader, streamLoader, todoManager, urlParser, view;

    if ($.browser.msie) {
      alert("IE Error.");
    }
    session = new com.uid.crowdcierge.Session;
    urlParser = new com.uid.crowdcierge.UrlParser({
      session: session
    });
    urlParser.readUrlParameters();
    streamLoader = new com.uid.crowdcierge.StreamLoader({
      session: session
    });
    streamLoader.load();
    stateLoader = new com.uid.crowdcierge.StateLoader({
      session: session
    });
    stateLoader.load();
    todoManager = new com.uid.crowdcierge.TodoManager({
      session: session
    });
    todoManager.updateTodo();
    view = new com.uid.crowdcierge.MainView({
      session: session
    });
    $('body').empty();
    $('body').append(view.$el);
    view.render();
    return console.log(session);
  }));

}).call(this);
