// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function() {
    var _ref;

    return com.uid.crowdcierge.FooterView = (function(_super) {
      __extends(FooterView, _super);

      function FooterView() {
        this._renderTask = __bind(this._renderTask, this);
        this._renderPreview = __bind(this._renderPreview, this);
        this._renderAdmin = __bind(this._renderAdmin, this);
        this.render = __bind(this.render, this);        _ref = FooterView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FooterView.prototype.className = 'footer';

      FooterView.prototype.render = function() {
        switch (this.model.get('taskType')) {
          case 'admin':
            return this._renderAdmin();
          case 'preview':
            return this._renderPreview();
          case 'task':
            return this._renderTask();
        }
      };

      FooterView.prototype._renderAdmin = function() {};

      FooterView.prototype._renderPreview = function() {};

      FooterView.prototype._renderTask = function() {};

      return FooterView;

    })(Backbone.View);
  })();

}).call(this);
