// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function() {
    var _ref;

    return com.uid.crowdcierge.HelpModal = (function(_super) {
      __extends(HelpModal, _super);

      function HelpModal() {
        this.renderContent = __bind(this.renderContent, this);
        this.renderHeader = __bind(this.renderHeader, this);
        this.intiialize = __bind(this.intiialize, this);        _ref = HelpModal.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      HelpModal.prototype.intiialize = function() {
        this.currentTaskModel = this.options.currentTaskModel;
        return this.className = this.className + ' modal-thin';
      };

      HelpModal.prototype.renderHeader = function() {
        return $('<div/>').text('What you can do to help');
      };

      HelpModal.prototype.renderContent = function() {
        return $('<div/>').text('What you can do to help');
      };

      return HelpModal;

    })(com.uid.crowdcierge.ModalView);
  })();

}).call(this);
