// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    var prepareSearchBox,
      _this = this;

    $('document').ready((function() {
      readUrlParameters();
      loadTaskState();
      loadUserData();
      initMap();
      loadStream();
      loadStateIntoInterface();
      initActMap();
      if ($.browser.msie) {
        alert("IE Error.");
      }
      $(window).resize(function() {
        if (typeof map !== "undefined" && map !== null) {
          map.Resize();
        }
        return setTimeout(typeof map !== "undefined" && map !== null ? map.SetCenter(map.GetCenter()) : void 0, 1000);
      });
      prepareSearchBox();
      prepCalendar();
      return showExplanationBox();
    }));
    prepareSearchBox = function() {
      var $sb;

      $sb = $("#searchBox");
      $sb.bind('keypress', (function(e) {
        var code;

        code = e.keyCode;
        if (code === 13) {
          return addSelect();
        }
      }));
      $sb.focus(function() {
        if ($sb.val() === emptyText) {
          $sb.val('');
          return $sb.css('color', 'gray');
        }
      });
      $sb.blur(function() {
        if ($sb.val() === '') {
          $sb.val(emptyText);
          return $sb.css('color', 'black');
        }
      });
      return readySearchBox();
    };
    return $.ui.autocomplete.prototype._renderItem = function(ul, item) {
      var re, t;

      re = new RegExp("^" + this.term);
      t = item.label.replace(re, "<span style='font-weight:bold;color:Blue;'>" + this.term + "</span>");
      return $("<li></li>").data("item.autocomplete", item).append("<a>" + item.value + "</a>").appendTo(ul);
    };
  })();

}).call(this);
