// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function() {
    var _ref;

    return com.uid.crowdcierge.ItineraryItem = (function(_super) {
      __extends(ItineraryItem, _super);

      function ItineraryItem() {
        _ref = ItineraryItem.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ItineraryItem.prototype.defaults = {
        activityCid: 0,
        activityShitId: null,
        startTime: 0
      };

      return ItineraryItem;

    })(Backbone.Model);
  })();

}).call(this);
