// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function() {
    var _ref;

    return com.uid.crowdcierge.ItineraryView = (function(_super) {
      __extends(ItineraryView, _super);

      function ItineraryView() {
        this.render = __bind(this.render, this);
        this.initialize = __bind(this.initialize, this);        _ref = ItineraryView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ItineraryView.prototype.className = 'itinerary-view';

      ItineraryView.prototype.initialize = function() {
        this.session = this.options.session;
        this.currentTaskModel = this.session.currentTaskModel;
        this.itineraryModel = this.session.itineraryModel;
        return this.travelTimeModel = this.session.travelTimeModel;
      };

      ItineraryView.prototype.render = function() {
        var source, template;

        this.$el.empty();
        source = $('#itinerary-view-template').html();
        template = Handlebars.compile(source);
        return this.$el.html(template());
      };

      return ItineraryView;

    })(Backbone.View);
  })();

}).call(this);
