// map variables
var map = null;
var newactmap = null;
var startPin = null;
var endPin = null;
var newactPin = null;
var viewactPin = null;
var findLayer = null;
var slRoute = null;
var actfindLayer = null;
var mapCenter = null;
var numTags = 0;
var waylayer = null;
var wayhash = [];
var waypointIcon = '../img/wp.gif'; // ../img/pin2.gif
var defaultZoom = 12;
var newactpinMoved = false;
var remainingRoute = [];
var longLegs = [];
var restDrive = null;
var restWalk = null;
var tolerance = 0.00005;