// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    return com.uid.crowdcierge.Session = (function() {
      function Session() {
        this.itineraryModel = new Backbone.Collection({
          model: com.uid.crowdcierge.ItineraryItem
        });
        this.activitiesModel = new Backbone.Collection({
          model: com.uid.crowdcierge.Activity
        });
        this.constraintsModel = new Backbone.Collection({
          model: com.uid.crowdcierge.Constraint
        });
        this.checkItemModel = new Backbone.Collection;
        this.currentTaskModel = new Backbone.Model;
      }

      return Session;

    })();
  })();

}).call(this);
