// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function() {
    var Session;

    return Session = (function() {
      function Session() {
        this.initialize = __bind(this.initialize, this);
      }

      Session.prototype.initialize = function() {
        this.itineraryModel = new Backbone.Collection;
        this.activitiesModel = new Backbone.Collection({
          model: ActivityModel
        });
        this.constraintsModel = new Backbone.Collection;
        this.systemModel = new Backbone.Collection;
        return this.checkItemModel = new Backbone.Collection;
      };

      return Session;

    })();
  })();

}).call(this);
